[package]
name = "bt2-sys"
version = "0.1.0"
edition = "2021"

[dependencies]
derive_more = { version = "1.0.0", features = ["deref", "deref_mut", "from"] }
thiserror = "1.0.64"

[build-dependencies]
bindgen = { version = "0.70.1", features = ["experimental"]}
cc = "1.0"
