[package]
name = "bt2-derive"
description = "Derive macros for bt2-sys"
version = "0.1.0"
edition = "2021"
authors.workspace = true
repository.workspace = true

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.89"
quote = "1.0.37"
syn = "2.0.85"
